#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


runApplication blockMesh
runParallel snappyHexMesh -overwrite

#runApplication transformPoints -translate '(0 0 0.0024)

#------------------------------------------------------------------------------